# Add 'repo' label to any root file changes
repo:
- '*'

# Add '@domain/core' label to any change within the 'core' package
# @domain/core:
# - package/core/*
# - package/core/**/*

modules:
- src/modules/**/*

submodules:
- src/submodules/**/*

baseType:
- src/modules/BaseType/*

baseMethod:
- src/modules/BaseMethod/*

source:
- any: ['src/**/*', '!src/docs/*']

utility:
- any: ['src/**/Utility/*']

linalg:
  - any: ['src/**/CSRMatrix/*', 'src/**/CSRSparsity/*', 'src/**/Lapack/*', 'src/**/OpenMP/*', 'src/**/RealMatrix/*', 'src/**/RealVector/*' ]